//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int CountryID { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
        public virtual City City11 { get; set; }
        public virtual City City3 { get; set; }
        public virtual City City12 { get; set; }
        public virtual City City4 { get; set; }
    }
}
