//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int ID { get; set; }
        public string Desc { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int DictID { get; set; }
        public int LangID { get; set; }
        public string SparseOne { get; set; }
        public string SparseTwo { get; set; }
    
        public virtual Locolization Locolization { get; set; }
        public virtual Category Category { get; set; }
    }
}
