//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Owners = new HashSet<Owner>();
        }
    
        public int UserID { get; set; }
        public string UserFirstNameEng { get; set; }
        public string UserLastNameEng { get; set; }
        public string UserFirstNameAr { get; set; }
        public string UserLastNameAr { get; set; }
        public string UserEmail { get; set; }
        public int PhoneNumber { get; set; }
        public int LangID { get; set; }
        public int AddressID { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Address Address { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner> Owners { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
