//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int OwnerID { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
