//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
    }
}
